--------------------------------------------------------
-- Archivo creado  - domingo-octubre-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLINICA
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."CLINICA" 
   (	"COD_CLINICA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"DIRECCION" CHAR(75 BYTE), 
	"COD_DEPARTAMENTO" NUMBER(*,0), 
	"COD_MUNICIPIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."DEPARTAMENTO" 
   (	"COD_DEPARTAMENTO" NUMBER(*,0), 
	"NOMBRE" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."EMPLEADO" 
   (	"COD_EMPLEADO" NUMBER(*,0), 
	"FECHA_CONTRATACION" DATE, 
	"PUESTO" VARCHAR2(25 BYTE), 
	"COD_PERSONA" NUMBER(*,0), 
	"COD_CLINICA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESPECIALIDAD
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."ESPECIALIDAD" 
   (	"COD_ESPECIALIDAD" CHAR(10 BYTE), 
	"NOMBRE" CHAR(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXPEDIENTE
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."EXPEDIENTE" 
   (	"COD_EXPEDIENTE" NUMBER(*,0), 
	"ID_AFILIADO" NUMBER(*,0), 
	"FECHA_CREACION" DATE, 
	"COD_CLINICA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."MEDICAMENTO" 
   (	"COD_MEDICAMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."MEDICO" 
   (	"COD_MEDICO" NUMBER(*,0), 
	"COD_ESPECIALIDAD" CHAR(10 BYTE), 
	"COD_EMPLEADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MUNICIPIO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."MUNICIPIO" 
   (	"COD_MUNICIPIO" NUMBER(*,0), 
	"NOMBRE" CHAR(30 BYTE), 
	"COD_DEPARTAMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."PACIENTE" 
   (	"ID_AFILIADO" NUMBER(*,0), 
	"COD_PERSONA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."PERSONA" 
   (	"COD_PERSONA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"CONYUGE" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"COD_MUNICIPIO" NUMBER(*,0), 
	"COD_DEPARTAMENTO" NUMBER(*,0), 
	"DUI" VARCHAR2(50 BYTE), 
	"PROFESION" VARCHAR2(50 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(25 BYTE), 
	"PADRE" VARCHAR2(100 BYTE), 
	"MADRE" VARCHAR2(100 BYTE), 
	"GENERO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETA
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."RECETA" 
   (	"COD_RECETA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."ROL" 
   (	"COD_ROL" NUMBER(*,0), 
	"NOMBRE" CHAR(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SIGNOSVITALES
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."SIGNOSVITALES" 
   (	"COD_SIGNOS" NUMBER(*,0), 
	"TEMPERATURA" FLOAT(10), 
	"ALTURA" FLOAT(10), 
	"PRESION" FLOAT(10), 
	"PULSO" FLOAT(10), 
	"ID_AFILIADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "TOOUSER"."USUARIO" 
   (	"COD_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(25 BYTE), 
	"CONTRASENA" VARCHAR2(64 BYTE), 
	"COD_ROL" NUMBER(*,0), 
	"COD_PERSONA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TOOUSER.CLINICA
SET DEFINE OFF;
REM INSERTING into TOOUSER.DEPARTAMENTO
SET DEFINE OFF;
Insert into TOOUSER.DEPARTAMENTO (COD_DEPARTAMENTO,NOMBRE) values (1,'Ahuachapán                   ');
REM INSERTING into TOOUSER.EMPLEADO
SET DEFINE OFF;
REM INSERTING into TOOUSER.ESPECIALIDAD
SET DEFINE OFF;
REM INSERTING into TOOUSER.EXPEDIENTE
SET DEFINE OFF;
REM INSERTING into TOOUSER.MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into TOOUSER.MEDICO
SET DEFINE OFF;
REM INSERTING into TOOUSER.MUNICIPIO
SET DEFINE OFF;
Insert into TOOUSER.MUNICIPIO (COD_MUNICIPIO,NOMBRE,COD_DEPARTAMENTO) values (1,'Ashapuco                      ',1);
REM INSERTING into TOOUSER.PACIENTE
SET DEFINE OFF;
REM INSERTING into TOOUSER.PERSONA
SET DEFINE OFF;
Insert into TOOUSER.PERSONA (COD_PERSONA,NOMBRE,APELLIDO,FECHA_NACIMIENTO,CONYUGE,DIRECCION,COD_MUNICIPIO,COD_DEPARTAMENTO,DUI,PROFESION,ESTADO_CIVIL,PADRE,MADRE,GENERO) values (1,'Luis','Guevara',to_date('23/10/16','DD/MM/RR'),null,'calle',1,1,'53668746-8',null,'casado',null,null,'M');
REM INSERTING into TOOUSER.RECETA
SET DEFINE OFF;
REM INSERTING into TOOUSER.ROL
SET DEFINE OFF;
Insert into TOOUSER.ROL (COD_ROL,NOMBRE) values (1,'Administrador                                     ');
REM INSERTING into TOOUSER.SIGNOSVITALES
SET DEFINE OFF;
REM INSERTING into TOOUSER.USUARIO
SET DEFINE OFF;
Insert into TOOUSER.USUARIO (COD_USUARIO,NOMBRE,CONTRASENA,COD_ROL,COD_PERSONA) values (1,'user','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',1,1);
Insert into TOOUSER.USUARIO (COD_USUARIO,NOMBRE,CONTRASENA,COD_ROL,COD_PERSONA) values (2,'daniel','bd3dae5fb91f88a4f0978222dfd58f59a124257cb081486387cbae9df11fb879',1,1);
--------------------------------------------------------
--  DDL for Index PK_CLINICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_CLINICA" ON "TOOUSER"."CLINICA" ("COD_CLINICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_DEPARTAMENTO" ON "TOOUSER"."DEPARTAMENTO" ("COD_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_EMPLEADO" ON "TOOUSER"."EMPLEADO" ("COD_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ESPECIALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_ESPECIALIDAD" ON "TOOUSER"."ESPECIALIDAD" ("COD_ESPECIALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EXPEDIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_EXPEDIENTE" ON "TOOUSER"."EXPEDIENTE" ("COD_EXPEDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEDICAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_MEDICAMENTO" ON "TOOUSER"."MEDICAMENTO" ("COD_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEDICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_MEDICO" ON "TOOUSER"."MEDICO" ("COD_MEDICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MUNICIPIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_MUNICIPIO" ON "TOOUSER"."MUNICIPIO" ("COD_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PACIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_PACIENTE" ON "TOOUSER"."PACIENTE" ("ID_AFILIADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_PERSONA" ON "TOOUSER"."PERSONA" ("COD_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RECETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_RECETA" ON "TOOUSER"."RECETA" ("COD_RECETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_ROL" ON "TOOUSER"."ROL" ("COD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SIGNOSVITALES
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_SIGNOSVITALES" ON "TOOUSER"."SIGNOSVITALES" ("COD_SIGNOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOOUSER"."PK_USUARIO" ON "TOOUSER"."USUARIO" ("COD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLINICA
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."CLINICA" ADD CONSTRAINT "PK_CLINICA" PRIMARY KEY ("COD_CLINICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."CLINICA" MODIFY ("COD_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."CLINICA" MODIFY ("COD_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."CLINICA" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."CLINICA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."CLINICA" MODIFY ("COD_CLINICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."DEPARTAMENTO" ADD CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("COD_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."DEPARTAMENTO" MODIFY ("COD_DEPARTAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."EMPLEADO" ADD CONSTRAINT "PK_EMPLEADO" PRIMARY KEY ("COD_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."EMPLEADO" MODIFY ("PUESTO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."EMPLEADO" MODIFY ("FECHA_CONTRATACION" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."EMPLEADO" MODIFY ("COD_EMPLEADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPECIALIDAD
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."ESPECIALIDAD" ADD CONSTRAINT "PK_ESPECIALIDAD" PRIMARY KEY ("COD_ESPECIALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."ESPECIALIDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."ESPECIALIDAD" MODIFY ("COD_ESPECIALIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."EXPEDIENTE" ADD CONSTRAINT "PK_EXPEDIENTE" PRIMARY KEY ("COD_EXPEDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."EXPEDIENTE" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."EXPEDIENTE" MODIFY ("ID_AFILIADO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."EXPEDIENTE" MODIFY ("COD_EXPEDIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."MEDICAMENTO" ADD CONSTRAINT "PK_MEDICAMENTO" PRIMARY KEY ("COD_MEDICAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."MEDICAMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."MEDICAMENTO" MODIFY ("COD_MEDICAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."MEDICO" ADD CONSTRAINT "PK_MEDICO" PRIMARY KEY ("COD_MEDICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."MEDICO" MODIFY ("COD_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."MEDICO" MODIFY ("COD_ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."MEDICO" MODIFY ("COD_MEDICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."MUNICIPIO" ADD CONSTRAINT "PK_MUNICIPIO" PRIMARY KEY ("COD_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."MUNICIPIO" MODIFY ("COD_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."MUNICIPIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."MUNICIPIO" MODIFY ("COD_MUNICIPIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."PACIENTE" ADD CONSTRAINT "PK_PACIENTE" PRIMARY KEY ("ID_AFILIADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."PACIENTE" MODIFY ("COD_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PACIENTE" MODIFY ("ID_AFILIADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."PERSONA" ADD CONSTRAINT "PK_PERSONA" PRIMARY KEY ("COD_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("COD_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("COD_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."PERSONA" MODIFY ("COD_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETA
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."RECETA" ADD CONSTRAINT "PK_RECETA" PRIMARY KEY ("COD_RECETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."RECETA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."RECETA" MODIFY ("COD_RECETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."ROL" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("COD_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."ROL" MODIFY ("COD_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIGNOSVITALES
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."SIGNOSVITALES" ADD CONSTRAINT "PK_SIGNOSVITALES" PRIMARY KEY ("COD_SIGNOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("ID_AFILIADO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("PULSO" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("PRESION" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("ALTURA" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("TEMPERATURA" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."SIGNOSVITALES" MODIFY ("COD_SIGNOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("COD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOOUSER"."USUARIO" MODIFY ("COD_ROL" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."USUARIO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TOOUSER"."USUARIO" MODIFY ("COD_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLINICA
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."CLINICA" ADD CONSTRAINT "FK_CLINICA_0" FOREIGN KEY ("COD_DEPARTAMENTO")
	  REFERENCES "TOOUSER"."DEPARTAMENTO" ("COD_DEPARTAMENTO") ENABLE;
  ALTER TABLE "TOOUSER"."CLINICA" ADD CONSTRAINT "FK_CLINICA_1" FOREIGN KEY ("COD_MUNICIPIO")
	  REFERENCES "TOOUSER"."MUNICIPIO" ("COD_MUNICIPIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."EMPLEADO" ADD CONSTRAINT "FK_EMPLEADO_0" FOREIGN KEY ("COD_PERSONA")
	  REFERENCES "TOOUSER"."PERSONA" ("COD_PERSONA") ENABLE;
  ALTER TABLE "TOOUSER"."EMPLEADO" ADD CONSTRAINT "FK_EMPLEADO_1" FOREIGN KEY ("COD_CLINICA")
	  REFERENCES "TOOUSER"."CLINICA" ("COD_CLINICA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."EXPEDIENTE" ADD CONSTRAINT "FK_EXPEDIENTE_0" FOREIGN KEY ("ID_AFILIADO")
	  REFERENCES "TOOUSER"."PACIENTE" ("ID_AFILIADO") ENABLE;
  ALTER TABLE "TOOUSER"."EXPEDIENTE" ADD CONSTRAINT "FK_EXPEDIENTE_1" FOREIGN KEY ("COD_CLINICA")
	  REFERENCES "TOOUSER"."CLINICA" ("COD_CLINICA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."MEDICO" ADD CONSTRAINT "FK_MEDICO_0" FOREIGN KEY ("COD_ESPECIALIDAD")
	  REFERENCES "TOOUSER"."ESPECIALIDAD" ("COD_ESPECIALIDAD") ENABLE;
  ALTER TABLE "TOOUSER"."MEDICO" ADD CONSTRAINT "FK_MEDICO_1" FOREIGN KEY ("COD_EMPLEADO")
	  REFERENCES "TOOUSER"."EMPLEADO" ("COD_EMPLEADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."MUNICIPIO" ADD CONSTRAINT "FK_MUNICIPIO_0" FOREIGN KEY ("COD_DEPARTAMENTO")
	  REFERENCES "TOOUSER"."DEPARTAMENTO" ("COD_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."PACIENTE" ADD CONSTRAINT "FK_PACIENTE_0" FOREIGN KEY ("COD_PERSONA")
	  REFERENCES "TOOUSER"."PERSONA" ("COD_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."PERSONA" ADD CONSTRAINT "FK_PERSONA_0" FOREIGN KEY ("COD_MUNICIPIO")
	  REFERENCES "TOOUSER"."MUNICIPIO" ("COD_MUNICIPIO") ENABLE;
  ALTER TABLE "TOOUSER"."PERSONA" ADD CONSTRAINT "FK_PERSONA_1" FOREIGN KEY ("COD_DEPARTAMENTO")
	  REFERENCES "TOOUSER"."DEPARTAMENTO" ("COD_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIGNOSVITALES
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."SIGNOSVITALES" ADD CONSTRAINT "FK_SIGNOSVITALES_0" FOREIGN KEY ("ID_AFILIADO")
	  REFERENCES "TOOUSER"."PACIENTE" ("ID_AFILIADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "TOOUSER"."USUARIO" ADD CONSTRAINT "FK_USUARIO_0" FOREIGN KEY ("COD_ROL")
	  REFERENCES "TOOUSER"."ROL" ("COD_ROL") ENABLE;
  ALTER TABLE "TOOUSER"."USUARIO" ADD CONSTRAINT "FK_USUARIO_1" FOREIGN KEY ("COD_PERSONA")
	  REFERENCES "TOOUSER"."PERSONA" ("COD_PERSONA") ENABLE;
