package entity;
// Generated 23-oct-2016 15:50:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clinicas generated by hbm2java
 */
@Entity
@Table(name="CLINICAS"
    ,schema="ALE1"
)
public class Clinicas  implements java.io.Serializable {


     private BigDecimal codclinica;
     private String nombre;
     private String direccion;
     private String telefono;

    public Clinicas() {
    }

	
    public Clinicas(BigDecimal codclinica) {
        this.codclinica = codclinica;
    }
    public Clinicas(BigDecimal codclinica, String nombre, String direccion, String telefono) {
       this.codclinica = codclinica;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
     @Id 

    
    @Column(name="CODCLINICA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodclinica() {
        return this.codclinica;
    }
    
    public void setCodclinica(BigDecimal codclinica) {
        this.codclinica = codclinica;
    }

    
    @Column(name="NOMBRE", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DIRECCION", length=60)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="TELEFONO", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


