package entity;
// Generated 10-23-2016 11:08:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clinica generated by hbm2java
 */
@Entity
@Table(name="CLINICA"
    ,schema="TOOUSER"
)
public class Clinica  implements java.io.Serializable {


     private BigDecimal codClinica;
     private Departamento departamento;
     private Municipio municipio;
     private String nombre;
     private String telefono;
     private String direccion;
     private Set<Expediente> expedientes = new HashSet<Expediente>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Clinica() {
    }

	
    public Clinica(BigDecimal codClinica, Departamento departamento, Municipio municipio, String nombre, String telefono) {
        this.codClinica = codClinica;
        this.departamento = departamento;
        this.municipio = municipio;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    public Clinica(BigDecimal codClinica, Departamento departamento, Municipio municipio, String nombre, String telefono, String direccion, Set<Expediente> expedientes, Set<Empleado> empleados) {
       this.codClinica = codClinica;
       this.departamento = departamento;
       this.municipio = municipio;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.expedientes = expedientes;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="COD_CLINICA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodClinica() {
        return this.codClinica;
    }
    
    public void setCodClinica(BigDecimal codClinica) {
        this.codClinica = codClinica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COD_DEPARTAMENTO", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COD_MUNICIPIO", nullable=false)
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="TELEFONO", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="DIRECCION", length=75)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clinica")
    public Set<Expediente> getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set<Expediente> expedientes) {
        this.expedientes = expedientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clinica")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


