package entity;
// Generated 10-23-2016 11:08:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name="ESPECIALIDAD"
    ,schema="TOOUSER"
)
public class Especialidad  implements java.io.Serializable {


     private String codEspecialidad;
     private String nombre;
     private Set<Medico> medicos = new HashSet<Medico>(0);

    public Especialidad() {
    }

	
    public Especialidad(String codEspecialidad, String nombre) {
        this.codEspecialidad = codEspecialidad;
        this.nombre = nombre;
    }
    public Especialidad(String codEspecialidad, String nombre, Set<Medico> medicos) {
       this.codEspecialidad = codEspecialidad;
       this.nombre = nombre;
       this.medicos = medicos;
    }
   
     @Id 

    
    @Column(name="COD_ESPECIALIDAD", unique=true, nullable=false, length=10)
    public String getCodEspecialidad() {
        return this.codEspecialidad;
    }
    
    public void setCodEspecialidad(String codEspecialidad) {
        this.codEspecialidad = codEspecialidad;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="especialidad")
    public Set<Medico> getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set<Medico> medicos) {
        this.medicos = medicos;
    }




}


