package entity;
// Generated 10-23-2016 01:47:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Medicamento generated by hbm2java
 */
@Entity
@Table(name="MEDICAMENTO"
    ,schema="TOOUSER"
)
public class Medicamento  implements java.io.Serializable {


     private BigDecimal codMedicamento;
     private String nombre;

    public Medicamento() {
    }

    public Medicamento(BigDecimal codMedicamento, String nombre) {
       this.codMedicamento = codMedicamento;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="COD_MEDICAMENTO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodMedicamento() {
        return this.codMedicamento;
    }
    
    public void setCodMedicamento(BigDecimal codMedicamento) {
        this.codMedicamento = codMedicamento;
    }

    
    @Column(name="NOMBRE", nullable=false, length=75)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


