package entity;
// Generated 10-23-2016 01:47:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name="MEDICO"
    ,schema="TOOUSER"
)
public class Medico  implements java.io.Serializable {


     private BigDecimal codMedico;
     private Especialidad especialidad;
     private Empleado empleado;

    public Medico() {
    }

    public Medico(BigDecimal codMedico, Especialidad especialidad, Empleado empleado) {
       this.codMedico = codMedico;
       this.especialidad = especialidad;
       this.empleado = empleado;
    }
   
     @Id 

    
    @Column(name="COD_MEDICO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodMedico() {
        return this.codMedico;
    }
    
    public void setCodMedico(BigDecimal codMedico) {
        this.codMedico = codMedico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COD_ESPECIALIDAD", nullable=false)
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COD_EMPLEADO", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


