package entity;
// Generated 10-23-2016 11:08:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="MUNICIPIO"
    ,schema="TOOUSER"
)
public class Municipio  implements java.io.Serializable {


     private BigDecimal codMunicipio;
     private Departamento departamento;
     private String nombre;
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Clinica> clinicas = new HashSet<Clinica>(0);

    public Municipio() {
    }

	
    public Municipio(BigDecimal codMunicipio, Departamento departamento, String nombre) {
        this.codMunicipio = codMunicipio;
        this.departamento = departamento;
        this.nombre = nombre;
    }
    public Municipio(BigDecimal codMunicipio, Departamento departamento, String nombre, Set<Persona> personas, Set<Clinica> clinicas) {
       this.codMunicipio = codMunicipio;
       this.departamento = departamento;
       this.nombre = nombre;
       this.personas = personas;
       this.clinicas = clinicas;
    }
   
     @Id 

    
    @Column(name="COD_MUNICIPIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(BigDecimal codMunicipio) {
        this.codMunicipio = codMunicipio;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COD_DEPARTAMENTO", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="NOMBRE", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="municipio")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="municipio")
    public Set<Clinica> getClinicas() {
        return this.clinicas;
    }
    
    public void setClinicas(Set<Clinica> clinicas) {
        this.clinicas = clinicas;
    }




}


