package entity;
// Generated 23-oct-2016 15:50:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pacientes generated by hbm2java
 */
@Entity
@Table(name="PACIENTES"
    ,schema="ALE1"
)
public class Pacientes  implements java.io.Serializable {


     private String idAfiliado;
     private String apellido;
     private String conyuge;
     private String direccion;
     private String dui;
     private String estadoCivil;
     private Date fechaNacimiento;
     private String madre;
     private String nombre;
     private String padre;
     private String profesion;

    public Pacientes() {
    }

	
    public Pacientes(String idAfiliado, String estadoCivil) {
        this.idAfiliado = idAfiliado;
        this.estadoCivil = estadoCivil;
    }
    public Pacientes(String idAfiliado, String apellido, String conyuge, String direccion, String dui, String estadoCivil, Date fechaNacimiento, String madre, String nombre, String padre, String profesion) {
       this.idAfiliado = idAfiliado;
       this.apellido = apellido;
       this.conyuge = conyuge;
       this.direccion = direccion;
       this.dui = dui;
       this.estadoCivil = estadoCivil;
       this.fechaNacimiento = fechaNacimiento;
       this.madre = madre;
       this.nombre = nombre;
       this.padre = padre;
       this.profesion = profesion;
    }
   
     @Id 

    
    @Column(name="ID_AFILIADO", unique=true, nullable=false, length=5)
    public String getIdAfiliado() {
        return this.idAfiliado;
    }
    
    public void setIdAfiliado(String idAfiliado) {
        this.idAfiliado = idAfiliado;
    }

    
    @Column(name="APELLIDO", length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="CONYUGE", length=50)
    public String getConyuge() {
        return this.conyuge;
    }
    
    public void setConyuge(String conyuge) {
        this.conyuge = conyuge;
    }

    
    @Column(name="DIRECCION", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="DUI", length=20)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="ESTADO_CIVIL", nullable=false, length=35)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NACIMIENTO", length=7)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="MADRE", length=20)
    public String getMadre() {
        return this.madre;
    }
    
    public void setMadre(String madre) {
        this.madre = madre;
    }

    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="PADRE", length=20)
    public String getPadre() {
        return this.padre;
    }
    
    public void setPadre(String padre) {
        this.padre = padre;
    }

    
    @Column(name="PROFESION", length=20)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }




}


