package entity;
// Generated 10-23-2016 11:08:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Signosvitales generated by hbm2java
 */
@Entity
@Table(name="SIGNOSVITALES"
    ,schema="TOOUSER"
)
public class Signosvitales  implements java.io.Serializable {


     private BigDecimal codSignos;
     private Paciente paciente;
     private double temperatura;
     private double altura;
     private double presion;
     private double pulso;

    public Signosvitales() {
    }

    public Signosvitales(BigDecimal codSignos, Paciente paciente, double temperatura, double altura, double presion, double pulso) {
       this.codSignos = codSignos;
       this.paciente = paciente;
       this.temperatura = temperatura;
       this.altura = altura;
       this.presion = presion;
       this.pulso = pulso;
    }
   
     @Id 

    
    @Column(name="COD_SIGNOS", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodSignos() {
        return this.codSignos;
    }
    
    public void setCodSignos(BigDecimal codSignos) {
        this.codSignos = codSignos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_AFILIADO", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="TEMPERATURA", nullable=false, precision=10, scale=0)
    public double getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(double temperatura) {
        this.temperatura = temperatura;
    }

    
    @Column(name="ALTURA", nullable=false, precision=10, scale=0)
    public double getAltura() {
        return this.altura;
    }
    
    public void setAltura(double altura) {
        this.altura = altura;
    }

    
    @Column(name="PRESION", nullable=false, precision=10, scale=0)
    public double getPresion() {
        return this.presion;
    }
    
    public void setPresion(double presion) {
        this.presion = presion;
    }

    
    @Column(name="PULSO", nullable=false, precision=10, scale=0)
    public double getPulso() {
        return this.pulso;
    }
    
    public void setPulso(double pulso) {
        this.pulso = pulso;
    }




}


