package entity;
// Generated 10-23-2016 11:08:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="TOOUSER"
)
public class Usuario  implements java.io.Serializable {


     private BigDecimal codUsuario;
     private Persona persona;
     private Rol rol;
     private String nombre;
     private String contrasena;

    public Usuario() {
    }

	
    public Usuario(BigDecimal codUsuario, Rol rol, String nombre, String contrasena) {
        this.codUsuario = codUsuario;
        this.rol = rol;
        this.nombre = nombre;
        this.contrasena = contrasena;
    }
    public Usuario(BigDecimal codUsuario, Persona persona, Rol rol, String nombre, String contrasena) {
       this.codUsuario = codUsuario;
       this.persona = persona;
       this.rol = rol;
       this.nombre = nombre;
       this.contrasena = contrasena;
    }
   
     @Id 

    
    @Column(name="COD_USUARIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(BigDecimal codUsuario) {
        this.codUsuario = codUsuario;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COD_PERSONA")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COD_ROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="NOMBRE", nullable=false, length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CONTRASENA", nullable=false, length=64)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


